# Site settings
author: Calvin McDowell
title: Starting my Software Engineer Journey!
header-img: img/home-bg.png
email: calvinmac40@hotmail.com
copyright_name: Calvin McDowell
description: > # this means to ignore newlines until "baseurl:"
  Where it all started
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: calvinmac40
github_username:  calvinmac40

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
